name: Updater
on:
  schedule:
    - cron:  '30 3 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1'
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}
        run: julia --project=docs docs/main.jl
      - name: Commit report
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'odow'
          git config --global user.email 'odow@users.noreply.github.com'
          git commit -am "Automated report"
          git push
