name: updater
on:
  issue_comment:
    types:
      - created
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.comment.body == '/update'}}
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1'
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.instantiate()'
      - name: Build and deploy
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: julia --project=docs docs/main.jl
      - name: Commit report
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'odow'
          git config --global user.email 'odow@users.noreply.github.com'
          git commit -am "Automated report"
          git push
